sudo: false
language: node_js
node_js: 10
cache:
  yarn : true
  directories:
    - node_modules
branches:
  only:
    - master
    - dev-branch
notifications:
  email: false
before_script:
  - npm prune
script:
  - npm run test:cover
after_success:
  - npm run report-coverage